version: '3.8'

services:
  app:
    build: .

    ports:
      - '3000:3000'

    volumes:
      - .:/usr/src/app

    depends_on:
      - db

  db:
    image: postgres

    environment:
      POSTGRES_DB: mydatabase

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: password

    ports:
      - '5432:5432'
